uptee/accounts/urls.py
from django.conf.urls import *

urlpatterns = patterns('accounts.views',
                       url(r'^login/$', 'login', name='login'),
                       url(r'^logout/$', 'logout', name='logout'),
                       url(r'^register/$', 'register', name='register'),
                       url(r'^settings/$', 'settings', name='settings'),
                       url(r'^settings/password/$', 'change_password', name='change_password'),
                       url(r'^users/$', 'users', name='users'),
                       url(r'^user/(?P<user_id>\d+)$', 'user', name='user'),
                       url(r'^activate/(?P<activation_key>[a-zA-Z0-9]{32})$', 'activate', name='activate'),
                       url(r'^recoverpassword/$', 'password_recover', name='password_recover'),
                       url(r'^recoverpassword/(?P<recover_key>[a-zA-Z0-9]{32})$', 'password_recover', name='password_recover'),
                       url(r'^recoverusername/$', 'username_recover', name='username_recover'),
                       )

uptee/blog/urls.py
from django.conf.urls import *

urlpatterns = patterns('blog.views',
    url(r'^$', 'blog_home', name='home'),
    url(r'^entry/(?P<slug>[-\w]+)/$', 'entry_detail', name='entry_detail'),
)

uptee/mod/urls.py
from django.conf.urls import *

urlpatterns = patterns('mod.views',
    url(r'^servers/$', 'server_list', name='server_list'),
    url(r'^servers/type:(?P<server_status>online|offline)$', 'server_list', name='server_list__type'),
    url(r'^servers/(?P<username>[\w.@+-]+)/$', 'server_list', name='user_server_list'),
    url(r'^servers/(?P<username>[\w.@+-]+)/type:(?P<server_status>online|offline)$', 'server_list', name='user_server_list__type'),
    url(r'^server/(?P<server_id>\d+)/$', 'server_detail', name='server_detail'),
    url(r'^server/(?P<server_id>\d+)/scoreboard/$', 'server_scoreboard', name='server_scoreboard'),
    url(r'^server/(?P<server_id>\d+)/editsettings/$', 'server_edit', name='server_edit'),
    url(r'^server/(?P<server_id>\d+)/uploadmap/$', 'upload_map', name='upload_map'),
    url(r'^server/(?P<server_id>\d+)/editvotes/$', 'server_edit_votes', name='server_edit_votes'),
    url(r'^server/(?P<server_id>\d+)/editrconcommands/$', 'server_edit_rcon_commands', name='server_edit_rcon_commands'),
    url(r'^server/(?P<server_id>\d+)/edittunings/$', 'server_tunes', name='server_tunes'),
    url(r'^server/(?P<server_id>\d+)/changemod/$', 'server_change_mod', name='server_change_mod'),
    url(r'^server/(?P<server_id>\d+)/showvotes/$', 'server_votes', name='server_votes'),
    url(r'^server/(?P<server_id>\d+)/editserverdescription/$', 'server_edit_description', name='server_edit_description'),
    url(r'^server/(?P<server_id>\d+)/moderators/$', 'server_moderators', name='server_moderators'),
    url(r'^server/(?P<server_id>\d+)/moderators/(?P<user_id>\d+)/$', 'server_edit_moderator', name='server_edit_moderator'),
    url(r'^server/(?P<server_id>\d+)/console/$', 'server_console', name='server_console'),
    url(r'^server/(?P<server_id>\d+)/downloadconfig/$', 'config_download', name='config_download'),
    url(r'^server/(?P<server_id>\d+)/events/$', 'events_ajax', name='events_ajax'),
    url(r'^server/(?P<server_id>\d+)/events/add/$', 'events_add_ajax', name='events_add_ajax'),
    url(r'^server/(?P<server_id>\d+)/events/delete/$', 'events_delete_ajax', name='events_delete_ajax'),
    url(r'^startstopserver/(?P<server_id>\d+)/$', 'start_stop_server', name='start_stop_server'),
    url(r'^updatesettings/(?P<server_id>\d+)/$', 'update_settings', name='update_settings'),
    url(r'^updatevotes/(?P<server_id>\d+)/$', 'update_votes', name='update_votes'),
    url(r'^updaterconcommands/(?P<server_id>\d+)/$', 'update_rcon_commands', name='update_rcon_commands'),
    url(r'^updatetunings/(?P<server_id>\d+)/$', 'update_tunes', name='update_tunes'),
    url(r'^server_info_update/(?P<server_id>\d+)/$', 'server_info_update_ajax', name='server_info_update_ajax'),
    url(r'^server_terminal_command/(?P<server_id>\d+)/$', 'terminal_command_ajax', name='terminal_command_ajax'),
    url(r'^server_terminal_receive/(?P<server_id>\d+)/$', 'terminal_receive_ajax', name='terminal_receive_ajax'),
    url(r'^map/(?P<map_id>\d+)/$', 'map_details', name='map_details'),
    url(r'^map/(?P<map_id>\d+)/download/$', 'map_download', name='map_download'),
    url(r'^map/(?P<map_id>\d+)/delete/$', 'delete_map', name='delete_map')
)

uptee/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.defaults import page_not_found, permission_denied, server_error
from django.views.generic import TemplateView
import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('blog.urls')),
    url(r'^', include('mod.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('messaging.urls')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^captcha/', include('captcha.urls')),
    (r'^comments/', include('django_comments.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^admin_tools/', include('admin_tools.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('django.views.defaults',
        (r'^403/$', permission_denied),
        (r'^404/$', page_not_found),
        (r'^500/$', server_error),
    )
    try:
        __import__('debug_toolbar')
    except ImportError:
        pass
    else:
        import debug_toolbar
        urlpatterns += patterns('',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

if settings.TESTING_STATE:
    urlpatterns += patterns('',
        url(r'^', include('testingstate.urls')),
    )

uptee/accounts/models.py
from datetime import date
from dateutil.relativedelta import relativedelta
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from settings import AVAILABLE_TEMPLATES, DEFAULT_TEMPLATE
from mod.models import Mod, Option, Server, Tune


def get_template(request):
    if not request.user.is_authenticated():
        return DEFAULT_TEMPLATE
    template = request.user.profile.template
    if template not in [template_[0] for template_ in AVAILABLE_TEMPLATES if template_[2] or request.user.is_staff]:
        template = DEFAULT_TEMPLATE
        request.user.profile.template = template
        request.user.profile.save()
    return template


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, related_name='profile')
    template = models.CharField(max_length=100, default=DEFAULT_TEMPLATE)
    allowed_mods = models.ManyToManyField(Mod, blank=True, related_name='users')

    GENDER_NONE = 1
    GENDER_MALE = 2
    GENDER_FEMALE = 3
    GEDGET_CHOICES = (
        (GENDER_NONE, 'Not saying'),
        (GENDER_MALE, 'Male'),
        (GENDER_FEMALE, 'Female'),
    )
    gender = models.IntegerField(choices=GEDGET_CHOICES, default=GENDER_NONE)
    publish_gender = models.BooleanField(default=False)
    birthday = models.DateField(blank=True, null=True, help_text='only your age will be shown (e.g. 15-20) | (YYYY-MM-DD)')
    publish_birthday = models.BooleanField(default=False)
    ingame_name = models.CharField(max_length=20, blank=True, null=True, default='')
    publish_ingame_name = models.BooleanField(default=False)
    fav_map = models.CharField(max_length=50, blank=True, null=True, default='', verbose_name='favorite map')
    publish_fav_map = models.BooleanField(default=False)
    fav_mod = models.CharField(max_length=20, blank=True, null=True, default='', verbose_name='favorite mod')
    publish_fav_mod = models.BooleanField(default=False)
    contact = models.CharField(max_length=100, blank=True, null=True, default='')
    publish_contact = models.BooleanField(default=False)
    website = models.URLField(blank=True, null=True, default='')
    publish_website = models.BooleanField(default=False)
    publish_name = models.BooleanField(default=False)

    def active_servers(self):
        return self.user.servers.filter(is_active=True)

    def online_servers(self):
        return self.user.servers.filter(is_active=True, online=True)

    def active_count(self):
        return len(self.user.servers.filter(is_active=True))

    def online_count(self):
        return len(self.user.servers.filter(is_active=True, online=True))

    @property
    def get_age(self):
        age = relativedelta(dt1=date.today(), dt2=self.birthday).years
        if age < 8:
            return '0-7'
        elif age < 13:
            return '8-12'
        elif age < 18:
            return '13-17'
        elif age < 22:
            return '18-21'
        elif age < 28:
            return '22-27'
        elif age < 38:
            return '28-37'
        elif age < 51:
            return '38-50'
        else:
            return 'near death'

    def __unicode__(self):
        possessive = '' if self.user.username.endswith('s') else 's'
        return u"{0}'{1} profile".format(self.user.username, possessive)


class Moderator(models.Model):
    server = models.ForeignKey(Server, related_name='moderators')
    user = models.ForeignKey(User, related_name='moderators')
    restart_allowed = models.BooleanField(default=False)
    edit_automatic_restart_allowed = models.BooleanField(default=False)
    edit_map_download_allowed = models.BooleanField(default=False)
    edit_votes_allowed = models.BooleanField(default=False)
    map_upload_allowed = models.BooleanField(default=False)
    console_allowed = models.BooleanField(default=False)
    edit_rcon_commands_allowed = models.BooleanField(default=False)
    allowed_options = models.ManyToManyField(Option, related_name='moderators')
    allowed_tunings = models.ManyToManyField(Tune, related_name='moderators')


class Activation(models.Model):  # also used for password recover
    user = models.OneToOneField(User, unique=True, related_name='activation')
    key = models.CharField(max_length=32, unique=True, null=True)


def post_user_save(instance, **kwargs):
    if kwargs['created']:
        profile = UserProfile(user=instance)
        profile.save()


post_save.connect(post_user_save, sender=User, dispatch_uid='accounts.models')

uptee/blog/models.py
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db import models
from markdown import markdown


class Entry(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, blank=True)
    content = models.TextField('Inhalt', help_text='You may use markdown.')
    content_html = models.TextField()

    PUBLISHED_STATUS = 1
    DRAFT_STATUS = 2
    HIDDEN_STATUS = 3
    STATUS_CHOICES = (
        (PUBLISHED_STATUS, 'published'),
        (DRAFT_STATUS, 'draft'),
        (HIDDEN_STATUS, 'hidden'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT_STATUS)

    def slugify_title(self):
        new_slug = slug = slugify(self.title) or "bad-title"
        # preventing slugs from being non-unique, wordpress-style
        n = 1
        while True:
            try:
                Entry.objects.get(slug=new_slug)
            except Entry.DoesNotExist:
                break
            n += 1
            if n != 1:
                new_slug = "{0}-{1}".format(slug, n)
        return new_slug

    class Meta:
        ordering = ['-created_at']

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = self.slugify_title()
        self.content_html = markdown(self.content)
        super(Entry, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return (
            'entry_detail',
            (),
            {'slug': self.slug},
        )

uptee/comments/forms.py
from django.contrib.comments.forms import CommentForm
from django.utils.html import escape
from markdown import markdown


class CommentMarkdownForm(CommentForm):

    def clean_comment(self):
        comment = super(CommentMarkdownForm, self).clean_comment()
        comment = escape(comment)
        comment = markdown(comment)
        return comment

uptee/messaging/forms.py
from django import forms
from fields import Html5CaptchaField
from html5input import Html5EmailInput


class ContactForm(forms.Form):
    email = forms.EmailField(required=True, widget=Html5EmailInput(attrs={'required': None}))
    message = forms.CharField(widget=forms.Textarea(attrs={'required': None}))
    captcha = Html5CaptchaField(required=True)

uptee/my_comments/forms.py
from django_comments.forms import CommentForm
from django.utils.html import escape
from markdown import markdown


class CommentMarkdownForm(CommentForm):

    def clean_comment(self):
        comment = super(CommentMarkdownForm, self).clean_comment()
        comment = escape(comment)
        comment = markdown(comment)
        return comment

uptee/testingstate/forms.py
from django import forms
from testingstate.models import TestingKey


class TestingForm(forms.Form):
    key = forms.CharField(label="Testing key")

    def __init__(self, *args, **kwargs):
        super(TestingForm, self).__init__(*args, **kwargs)
        self.testing_key = None

    def clean_key(self):
        key = self.cleaned_data['key']
        try:
            self.testing_key = TestingKey.objects.get(key=key)
        except TestingKey.DoesNotExist:
            raise forms.ValidationError("Wrong key!")
        if self.testing_key.is_used:
            raise forms.ValidationError("That key has been used already!")
        return key

    def save(self):
        self.testing_key.is_used = True
        self.testing_key.save()


class MoreKeysForm(forms.Form):
    keys_num = forms.IntegerField(label="Number of keys to generate", min_value=1, max_value=10)

    def __init__(self, *args, **kwargs):
        super(MoreKeysForm, self).__init__(*args, **kwargs)
        self.new_keys = []

    def save(self):
        n = self.cleaned_data.get('keys_num')
        while n:
            k = TestingKey.objects.create()
            self.new_keys.append(k.key)
            n -= 1

uptee/blog/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from blog.models import Entry


def blog_home(request):
    if request.user.is_staff or request.user.is_superuser:
        entries = Entry.objects.exclude(status=Entry.DRAFT_STATUS)
    else:
        entries = Entry.objects.filter(status=Entry.PUBLISHED_STATUS)
    return render_to_response('blog/home.html', {'entry_list': entries}, context_instance=RequestContext(request))


def entry_detail(request, slug):
    if request.user.is_staff or request.user.is_superuser:
        entries = Entry.objects.exclude(status=Entry.DRAFT_STATUS)
    else:
        entries = Entry.objects.filter(status=Entry.PUBLISHED_STATUS)
    entry = get_object_or_404(
        entries.select_related(),
        slug=slug
    )
    return render_to_response('blog/entry_detail.html', {'entry': entry}, context_instance=RequestContext(request))

uptee/messaging/views.py
from django.contrib import messages
from django.core.mail import mail_admins
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.template import RequestContext
from messaging.forms import ContactForm
from settings import ADMINS, DEBUG


def contact(request):
    admins_available = True if ADMINS else False
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            msg = u'From: {0}\r\n\r\nMessage: {1}'.format(form.cleaned_data['email'], form.cleaned_data['message'])
            mail_admins('User contact', msg, fail_silently=not DEBUG)
            messages.success(request, 'Your message has been sent.')
            return HttpResponseRedirect(reverse('home'))
    return render_to_response('messaging/contact.html', {
            'form': form,
            'admins_available': admins_available,
        }, context_instance=RequestContext(request))

uptee/testingstate/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render_to_response
from django.template import RequestContext
from testingstate.forms import MoreKeysForm


@login_required
def generate_testing_keys(request):
    if not request.user.is_staff:
        raise Http404
    new_keys = None
    form = MoreKeysForm()
    if request.method == 'POST':
        form = MoreKeysForm(request.POST)
        if form.is_valid():
            form.save()
            new_keys = form.new_keys
            messages.success(request, "Created {0} new key{1}!".format(len(new_keys), '' if len(new_keys) == 1 else 's'))
    return render_to_response('testingstate/generate_testing_keys.html', {
            'new_keys': new_keys,
            'form': form,
        }, context_instance=RequestContext(request))

uptee/templates/simpleflat/accounts/activate.html
{% extends "base.html" %}

{% block title %}upTee - Activate{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'User Activation' 'activate' '00000000000000000000000000000000' %}
{% endblock %}

{% block content %}

<div class="contentBox w500">
    <div class="contentHeadline">User activation</div>
    <div class="content">
        <p>Your account has been successfully activated. You may now login.</p>
    </div>
</div>

{% endblock %}

uptee/templates/simpleflat/accounts/login.html
{% extends "base.html" %}


{% block body %}

<div id="headermenu">
    <ul class="left">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'server_list' %}">Server List</a></li>
        <li><a href="{% url 'users' %}">User List</a></li>
    </ul>
</div>
        
<div id="login_messages">
    {% include "messages.html" %}
</div>

<div id="loginBox">

    <div class="headline">
        <img src="{{ STATIC_URL }}simpleflat/img/upteelogo.png">
        <p>Login to upTee</p>
    </div>

    <div id="loginContainer">
        <form action="" method="post">
            <input type="hidden" name="csrfmiddlewaretoken" value="{% with csrf_token as csrf_token_clean %}{{ csrf_token_clean }}{% endwith %}">

            <div class="formBox">
                <input class="iconUsername" type="text" name="username" value="" id="username" required="" placeholder="Username">
            </div>

            <div class="formBox">
                <input class="iconPassword" type="password" name="password" value="" id="password" required="" placeholder="Password">
            </div>
            <div class="clear"></div>


            <div class="submitBox">
                <input class="button positive bgGreen"  type="submit" value="Login">
                <input type="hidden" name="next" value="{{ next }}">
            </div>
        </form>
    </div>
</div>
{% endblock body %}

uptee/templates/simpleflat/accounts/password_change.html
{% extends "base.html" %}

{% comment %}
context variables:
    form
{% endcomment %}

{% block title %}upTee - Change password{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'Settings' 'settings' %}
    {% add_crumb 'Change password' 'change_password' %}
{% endblock %}

{% block content %}

<div class="contentBox w400">
    <div class="contentHeadline">Change Password</div>
    <div class="content">
        <form method="post" action="{{ request.path }}">
            <input type="hidden" name="csrfmiddlewaretoken" value="{% with csrf_token as csrf_token_clean %}{{ csrf_token_clean }}{% endwith %}">
             <table class="formTable">
                <tbody>
                    {% for field in form %}
                    <tr>
                        <th>{{ field.label }}:</th>
                        <td>{{ field.errors }}<input class="{% if field.errors %} error{% endif %}" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" value="{{ field.value|default_if_none:"" }}" id="{{ field.id_for_label }}"{% for key, value in field.field.widget.attrs.items %} {{ key }}="{{ value }}"{% endfor %}></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <input class="button" type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

uptee/templates/simpleflat/accounts/password_recover.html
{% extends "base.html" %}

{% comment %}
context variables:
    form
{% endcomment %}

{% block title %}upTee - Recover Password{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'Settings' 'settings' %}
    {% add_crumb 'Recover password' 'password_recover' %}
{% endblock %}

{% block content %}

{% load captcha_tag %}
{% captcha_tag %}

<div class="contentBox">
    <div class="contentHeadline">Recover Password</div>
    <div class="content">
        <p>Insert your username to recover the password.</p>
        <form method="post" action="{{ request.path }}">
            <input type="hidden" name="csrfmiddlewaretoken" value="{% with csrf_token as csrf_token_clean %}{{ csrf_token_clean }}{% endwith %}">
            <table class="formTable">
                <tbody>
                    {% for field in form %}
                        {% if field.name != 'captcha' %}
                        <tr>
                            <th>{{ field.label }}:</th>
                            <td>{{ field.errors }}<input class="{% if field.errors %} error{% endif %}" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" value="{{ field.value|default_if_none:"" }}" id="{{ field.id_for_label }}"{% for key, value in field.field.widget.attrs.items %} {{ key }}="{{ value }}"{% endfor %}></td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    <tr>
                        <th>
                            <img class="captcha" alt="captcha" src="{% url 'captcha-image' captcha_key %}"><input id="id_captcha_0" type="hidden" value="{{ captcha_key }}" name="captcha_0">
                        </th>
                        <td>
                            {{ form.captcha.errors }}<input class="icon_captcha{% if form.captcha.errors %} error{% endif %}" type="text" name="captcha_1" value="" id="id_captcha_1" required="">
                        </td>
                    </tr>
                </tbody>
            </table>
            <input class="button" type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

uptee/templates/simpleflat/accounts/register.html
{% extends "base.html" %}

{% comment %}
context variables:
    register_form
    testing_form
{% endcomment %}

{% block body %}

{% load captcha_tag %}
{% captcha_tag %}

<div id="headermenu">
    <ul class="left">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'server_list' %}">Server List</a></li>
        <li><a href="{% url 'users' %}">User List</a></li>
    </ul>
</div>
        
<div id="loginBox">
    <div class="headline">
        <img src="{{ STATIC_URL }}simpleflat/img/upteelogo.png">
        <p>Register to upTee</p>
    </div>
    <div id="registerContainer">
        
        <form method="post" action="{{ request.path }}">
            <input type="hidden" name="csrfmiddlewaretoken" value="{% with csrf_token as csrf_token_clean %}{{ csrf_token_clean }}{% endwith %}">

            {% if testing_form %}
                <div class="descriptionBox">
                    {{ testing_form.key.label_tag }}
                </div>

                <div class="formBox">
                    <input class="{% if testing_form.key.errors %} error{% endif %}" type="text" name="key" value="{{ testing_form.key.value|default_if_none:"" }}" id="id_key" required=""/>
                    {{ testing_form.key.errors }}
                </div>
            {% endif %}

            {% for field in register_form %}
                {% if field.name != 'captcha' %}
                    <div class="formBox">
                        <input class="{% if field.errors %} error{% endif %}" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" value="{{ field.value|default_if_none:"" }}" id="{{ field.id_for_label }}"{% for key, value in field.field.widget.attrs.items %} {{ key }}="{{ value }}"{% endfor %}/>
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}

            <div class="descriptionBox">
                <img class="captcha" alt="captcha" src="{% url 'captcha-image' captcha_key %}"><input id="id_captcha_0" type="hidden" value="{{ captcha_key }}" name="captcha_0">
            </div>

            <div class="formBox">
                <input class="icon_captcha{% if register_form.captcha.errors %} error{% endif %}" type="text" name="captcha_1" value="" id="id_captcha_1" required="">
                {{ register_form.captcha.errors }}
            </div>

            <div class="clear"></div>
            <div class="submitBox">
                <input class="button positive bgGreen" type="submit" value="Register">
                <input type="hidden" name="next" value="{{ request.path }}">
            </div>
        </form>

    </div>
</div>


{% endblock body %}

uptee/templates/simpleflat/accounts/user_profile.html
{% extends "base.html" %}

{% load possessive %}
{% load split %}
{% load get_option %}
{% load gravatar %}

{% comment %}
context variables:
    user_profile
{% endcomment %}

{% block title %}upTee - {{ user_profile.username|possessive }} profile{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'Users' 'users' %}
    {% with user_profile_breadcrumb=user_profile.username|possessive|add:' profile' %}
        {% add_crumb user_profile_breadcrumb 'user' user_profile.id %}
    {% endwith %}
{% endblock %}

{% block content %}

<div class="contentBox w290">
    <div class="contentHeadline">{{ user_profile.username }}</div>
    <div class="content">
    <img class="userProfile" src="{% gravatar_for_user user_profile 250 %}">
    <p class="joinLable"><i class="icon-calendar"></i> Joined on {{ user_profile.date_joined|date:"N t, Y" }}</p>
</div>
</div>

<div class="contentBox w450">
    <div class="contentHeadline">Infos</div>
    <div class="content">
         <table class="bordered">
            <tbody>
                {% if user_profile.first_name %}
                    {% if user_profile.profile.publish_name or user.is_authenticated %}
                    <tr>
                        <th>Name:</th>
                        <td>{{ user_profile.first_name }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.ingame_name %}
                    {% if user_profile.profile.publish_ingame_name or user.is_authenticated %}
                    <tr>
                        <th>Ingame name:</th>
                        <td>{{ user_profile.profile.ingame_name }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.website %}
                    {% if user_profile.profile.publish_website or user.is_authenticated %}
                    <tr>
                        <th>Website:</th>
                        <td><a href="{{ user_profile.profile.website }}" target="_blank">{{ user_profile.profile.website }}</a></td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.contact %}
                    {% if user_profile.profile.publish_contact or user.is_authenticated %}
                    <tr>
                        <th>Contact:</th>
                        <td>{{ user_profile.profile.contact }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.fav_mod %}
                    {% if user_profile.profile.publish_fav_mod or user.is_authenticated %}
                    <tr>
                        <th>Favorite mod:</th>
                        <td>{{ user_profile.profile.fav_mod }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.fav_map %}
                    {% if user_profile.profile.publish_fav_map or user.is_authenticated %}
                    <tr>
                        <th>Favorite map:</th>
                        <td>{{ user_profile.profile.fav_map }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.gender != 1 %}
                    {% if user_profile.profile.publish_gender or user.is_authenticated %}
                    <tr>
                        <th>Gender:</th>
                        <td>{{ user_profile.profile.get_gender_display }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if user_profile.profile.birthday %}
                    {% if user_profile.profile.publish_birthday or user.is_authenticated %}
                    <tr>
                        <th>Age:</th>
                        <td>{{ user_profile.profile.get_age }}</td>
                    </tr>
                    {% endif %}
                {% endif %}
                <tr>
                    <th>Servers:</th>
                    <td>{{ user_profile.profile.active_servers|length }}</td>
                </tr>
                <tr>
                    <th>Online servers:</th>
                    <td>{{ user_profile.profile.online_servers|length }}</td>
                </tr>
            </tbody>
        </table>
        <br>
        {% if user.is_authenticated and user == user_profile %}
            <p><a class="link_button" href="{% url 'settings' %}">Edit profile</a></p>
        {% endif %}
    </div>
</div>



{% endblock %}